### PR TITLE
Fixes #525 | add aggregate functions for collections

### LINKED ISSUE #525: add aggregation functions (3.2) for efficiently getting the nth of a aggregation
So instead of doing ´collect(n)[0..5]` or `head(collect(n))`

* `apoc.first(n)`
* `apoc.last(n)`
* `apoc.nth(n,skip)`
* `apoc.subset(n,skip,limit)`

### PR DESCRIPTION
**Pull request by zygm0nt**

### CODE REVIEW

**Comment by jexp** [comment]
Hi, sorry, that's not what I meant.
I was referring to the new type of AggregationFunction that are available in Neo4j 3.2.

http://neo4j.com/docs/developer-manual/current/extending-neo4j/cypher-functions/#user-defined-aggregation-functions

They get called per row, and then at the end of the query.
So they would just either take the first, last, or nth value and ignore all the others and return those value(s) then in the end.

**Comment by zygm0nt** [comment]
Ok, I see - I'll look into the docs and fix this. Didn't know about the UDF

**Comment by jexp** [comment]
Do you think you find time today for your two PRs? I would want to release tonight.

**Comment by zygm0nt** [comment]
No, sorry - I've been planing to code this tomorrow night. 

But as for my PR's there are three of them. 

https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/593
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/525
and this one.

**Comment by jexp** [comment]
@zygm0nt ping on an update?

**Comment by jexp** [comment]
Added them here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/76db5469c9ad4f73b56703ff4f8fe441cdfd73bb

**Pull request closed without merging**
