### PR TITLE
Consistent Label order (#579)

### PR DESCRIPTION
**Pull request by dodie**
fix issue #579: consistent Label order using export csv

### CODE REVIEW

**Comment by dodie** [comment]
Hi, I've submitted a PR for this issue, could you review the changes, please?

**Comment by jexp** [comment]
Can you please sign our CLA ? https://neo4j.com/developer/cla/

**Comment by dodie** [comment]
Ok, I've signed it.

**Comment by jexp** [comment]
Thanks a lot !

**Pull request merged**
