### PR TITLE
Add doc for formatTimeZone in GitHub Pages site

### PR DESCRIPTION
**Pull request by ADTC**
GitHub Pages change related to #42 and #43

### CODE REVIEW

**Comment by ikwattro** [comment]
Can you add a link referencing the possible values. I think it can help beginners. Thx

**Comment by ADTC** [comment]
Would this [Wikipedia page](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) suffice? I found other lists, but they are blogs and tutorial. I think the Wikipedia would always be the most up to date, due to its nature.

**Comment by ikwattro** [comment]
Yes sure very good. Thanks !

**Comment by ADTC** [comment]
Damn it, I'm not sure how to add up the link there. Should I do:

[Full names](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) are recommended.

Or

Full names are recommended. You can view a list of full names in [this Wikipedia page](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

**Comment by ikwattro** [comment]
Second looks ok to me

**Comment by ADTC** [comment]
Done :)

**Comment by jexp** [comment]
merged manually

**Pull request closed without merging**
