### PR TITLE
Fixes #428 - Missing detailed documentation for Create procedures

### LINKED ISSUE #428: Missing detailed documentation for Create procedures
part of #331

### PR DESCRIPTION
**Pull request by DanielBerton**

### CODE REVIEW

**Comment by jexp** [comment]
Can we make sure we have the queries in the pics also available as `[source,cypher]` texts?

**Comment by jexp** [comment]
all those should *not* go into overview.adoc but into a dedicated page.

**Comment by DanielBerton** [comment]
@jexp we have moved all to the new file `create-virtual-nodes-rels.adoc` ,we verified and 
 every pic has the relative statement source

**Comment by jexp** [comment]
@DanielBerton could you please rebase this PR?

**Comment by DanielBerton** [comment]
@jexp rebased

**Pull request merged**
