### PR TITLE
Date test fix attempt #2

### LINKED ISSUE #16: Unit test failure on maven clean install: testfieldsCustomFormat(apoc.date.DateTest)
I'm seeing the following unit test failure on installing neo4j-apoc-procedures:

`Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.716 sec <<< FAILURE!
testfieldsCustomFormat(apoc.date.DateTest)  Time elapsed: 0.148 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:&lt;E[ET]&gt; but was:&lt;E[urope/Bucharest]&gt;
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at apoc.date.DateTest.lambda$testfieldsCustomFormat$15(DateTest.java:190)
	at apoc.util.TestUtil.lambda$testCall$0(TestUtil.java:39)
	at apoc.util.TestUtil.testResult(TestUtil.java:51)
	at apoc.util.TestUtil.testCall(TestUtil.java:36)
	at apoc.util.TestUtil.testCall(TestUtil.java:24)
	at apoc.date.DateTest.testfieldsCustomFormat(DateTest.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running apoc.get.GetTest
...
Failed tests:   testfieldsCustomFormat(apoc.date.DateTest): expected:&lt;E[ET]&gt; but was:&lt;E[urope/Bucharest]&gt;`

Running on Mac OS X 10.11.4 with jdk1.8.0_92.jdk.

### PR DESCRIPTION
**Pull request by tkroman**
Fixes #16 now

### CODE REVIEW

**Comment by jexp** [comment]
I'm still scared to try it out :) could you rebase it and we'll see if travis gets green?

**Comment by tkroman** [comment]
@jexp I accidentally committed with the incorrect account, so there's a weird commit history now. Considering you mostly accept this in a manual fashion, would that be a problem?

**Comment by ikwattro** [comment]
@tkroman What's the status, do you want us to merge manually ?

**Comment by tkroman** [comment]
@ikwattro If that will make git log look prettier than it would look otherwise (which I think it will). Anyway, there might be conflicts with #43.
_Most importantly_, note that this PR not only brings test fixes, but also switches to a `ZoneId#getDisplayName()`, which should be more reliable and environment-independent than now.

**Comment by ADTC** [comment]
@tkroman I looked at your change in this PR. As I didn't make any changes in the same area, I don't expect any conflicts. :smile:

**Comment by ikwattro** [comment]
I tend to agree also. I prefer to keep history, or ask the author to squash itself.

**Comment by ikwattro** [comment]
I'll check with the team about merging locally / squash etc. For now I followed what was done by MH until now. Thanks @ADTC and @tkroman for your contributions. 

@ADTC I'm not aware about the releasing policy yet, however I can send you the jar via PM on Slack.

**Pull request closed without merging**
