### PR TITLE
Fixes #1383: Add procedure to compare indexes and constraints

### LINKED ISSUE #1383: Add procedure to compare indexes and constraints
Add procedure to compare indexes and constraints
thanks to @JMHReif for pointing this out!

### PR DESCRIPTION
**Pull request by vga91**
Fixes #1383

Refactored `core` to reuse code, but the actual procedure is located in `full`

### CODE REVIEW

**Comment by jexp** [comment]
No docs?

**Review by ncordon — CHANGES_REQUESTED** [review]
As @jexp was saying we should have docs here

**Comment by ncordon** [comment]
Given we don't control extended anymore, this is out of Cypher's Surface court and I will unassign myself

**Comment by vga91** [comment]
Closed in favor of https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3768

**Pull request closed without merging**
