### PR TITLE
Cherry-pick add a new after-async or async phase to triggers

### LINKED ISSUE #1731: afterAsync phase trigger from 4.0~4.1 to 4.2 and 4.3
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
APOC 4.2.0.0 and 4.3.0-rc01 was missing afterAsync that once implement in 4.0.0.18 and 4.1.0.2 with PR #1573.

<https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.1/core/src/main/java/apoc/trigger/TriggerHandler.java#L44>

## Actual Behavior (Mandatory)
afterAsync phase was missing from trigger handler both on branch 4.2 and 4.3.

<https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.2/core/src/main/java/apoc/trigger/TriggerHandler.java>
<https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.3/core/src/main/java/apoc/trigger/TriggerHandler.java>

### Versions

  - OS:
  - Neo4j: 4.2.0
  - Neo4j-Apoc: 4.2.0.0

### PR DESCRIPTION
**Pull request by ivangreene**
Fixes #1731 

Just cherry picked the commit from https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1573 and resolved the conflicts

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - Cherry pick the commit from https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1573

### CODE REVIEW

**Comment by mneedham** [comment]
Hey @ivangreene, 

I think the changes in this PR are already merged into the 4.1 branch. At least when I check TriggerHandler I can see most of the changes - https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.1/core/src/main/java/apoc/trigger/TriggerHandler.java

Can you confirm?

Cheers, Mark

**Comment by ivangreene** [comment]
@mneedham yeah I cherry picked this commit from the 4.1 branch, but this PR is targeting 4.2. It looks like 4.2 and 4.3 branches were created from 4.1 before this change landed, so they never made it there: https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.2/core/src/main/java/apoc/trigger/TriggerHandler.java

**Comment by ivangreene** [comment]
Just rebased to resolve the conflicts

**Comment by mneedham** [comment]
ah got it. That makes more sense!

**Pull request merged**
