### PR TITLE
extract credentials and make them a header when passed in url

### PR DESCRIPTION
**Pull request by ikwattro**

### CODE REVIEW

**Comment by jexp** [comment]
Can you squash the commits?

**Comment by jexp** [comment]
No need to pass in headers. Just return a new map, something like `return MapUtil.map(key,value)`

**Comment by jexp** [comment]
No need to pass in headers. Just return a new map, something like `return MapUtil.map(key,value)`

**Comment by jexp** [comment]
No need to pass in headers. Just return a new map, something like `return MapUtil.map(key,value)`

**Comment by jexp** [comment]
No need to pass in headers. Just return a new map, something like `return MapUtil.map(key,value)`

**Comment by jexp** [comment]
No need to pass in headers. Just return a new map, something like `return MapUtil.map(key,value)`

**Comment by jexp** [comment]
No need to pass in headers. Just return a new map, something like `return MapUtil.map(key,value)`

**Comment by ikwattro** [comment]
ok !

**Comment by ikwattro** [comment]
ok !

**Comment by ikwattro** [comment]
Thanks will do

**Comment by ikwattro** [comment]
Thanks will do

**Comment by jexp** [comment]
No need to pass in headers. Just return a new map, something like `return MapUtil.map(key,value)`

**Comment by jexp** [comment]
Sorry, Safari + shit internet.

**Comment by jexp** [comment]
Build failed, probably needs to check if headers is null, I think there is a map.merge Function in utils somewhere that takes care of that.

**Comment by ikwattro** [comment]
There is but doesn't seem to handle `null` instances. Test fixed

**Comment by jexp** [comment]
Thanks a lot

**Pull request merged**
