### PR TITLE
Fixes typos and missing function reference

### PR DESCRIPTION
**Pull request by mariusconjeaud**
## Proposed Changes

 - Add apoc.schema.node.indexExists to function reference list in apoc.schema page
 - Fixes typos (sortPathsByDistance instead of sortByDistance) in apoc.spatial pages

### CODE REVIEW

**Comment by conker84** [comment]
@mariusconjeaud can you fix the typo also in `Distance.java`?
Thank you so much!

**Comment by mariusconjeaud** [comment]
> @mariusconjeaud can you fix the typo also in `Distance.java`?
> Thank you so much!

Done

**Review by conker84 — APPROVED** [review]
@mariusconjeaud thank you so much!
Just one last thing did you sign the [CLA](https://neo4j.com/developer/cla/)

**Comment by conker84** [comment]
@mariusconjeaud sorry i just realized that you don't need it!

**Pull request merged**
