### PR TITLE
Upgrade compiler to 1.0.3

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by fbiville** [comment]
This adds several warnings to the build now, as many procedure rely on undocumented-yet-working types :-)

**Comment by jexp** [comment]
Which ones concretely?

**Comment by jexp** [comment]
Those warnings are not helpful in APOC, can we configure them off for the @Context injections?

**Comment by fbiville** [comment]
@jexp I can introduce an option to disable them :-)

**Comment by jexp** [comment]
Please do

Von meinem iPhone gesendet

**Comment by fbiville** [comment]
Done :-)

**Comment by fbiville** [comment]
Hi, I think it should run again, maybe the 1.0.3 release was not visible yet when I pushed the change.

**Comment by ikwattro** [comment]
@fbiville build restarted https://travis-ci.org/neo4j-contrib/neo4j-apoc-procedures/builds/162558798

**Comment by ikwattro** [comment]
@fbiville build green :)

**Comment by fbiville** [comment]
Thanks!

**Pull request merged**
