### PR TITLE
Refactored path expander label matching and added support for compound labels and known end nodes

### PR DESCRIPTION
**Pull request by InverseFalcon**

### CODE REVIEW

**Comment by InverseFalcon** [comment]
I don't believe my changes are related to the failed test, something else is going on.

**Comment by jexp** [comment]
Does this need a docs update @InverseFalcon ?

**Comment by InverseFalcon** [comment]
A small one, yes, I'll check that in.

**Comment by InverseFalcon** [comment]
Tests in BoltTest are throwing exceptions, unrelated to my checkin.

**Pull request merged**
