### PR TITLE
more general encoding for _search fixes #372

### LINKED ISSUE #372: apoc.es.query should encode query parameters correctly even if there is no query_string
1. All these query have to work properly:

- /index/type/_search?size=1&scroll=1m&_source=true
- /index/type/_search?q=*
- /index/type/_search?q=name%3ANeo4j
- /index/type/_search? (--> /index/type/_search)
- /index/type/_search?q=name:Neo4j
- /index/type/_search?q=name:*

2. Add more tests in order to cover more use cases for Elasticsearch _search API

### PR DESCRIPTION
**Pull request by albertodelazzari**

### CODE REVIEW

**Comment by jexp** [comment]
mixes two issues (objectID) and _search

**Comment by albertodelazzari** [comment]
Ok, got it. I remove the wrong commit and update the PR

**Comment by inserpio** [comment]
@jexp this should be closeable... no?

**Comment by jexp** [comment]
@albertodelazzari ping :)

**Comment by albertodelazzari** [comment]
@jexp the wrong commit was reverted. There are changes only to the files related to ES apoc so there should be no problem to merge it with the base branch. Is there something else I am missing?

**Pull request merged**
