### PR TITLE
Use Neo4j Stored Procedure compiler

### PR DESCRIPTION
**Pull request by fbiville**
This Pull Request is meant as a discussion starter and needs
some clarifications before it can be merged.

### CODE REVIEW

**Comment by fbiville** [comment]
I would like to continue the conversation I started with @jexp here.
There are mainly two kinds of error that are reported by the plugin:

1. undocumented procedure input type: `Node`, `Relationship` and `Path` are not listed as supported procedure types, that's why the compiler complains about it
1. Map erasure: it seems the runtime accepts `Map` instances other than the documented `Map<String,Object>`

I'll send a documentation update PR this week and update the compiler accordingly.
About point 2, I'm still unclear about what to do. In my opinion, the compiler is strict and should be. 

Usage of raw types such as `Map` should definitely be discouraged (and people don't have to use the compiler if they don't want compile-time checks).
For the other map errors, I'm not sure. The docs clearly state that people should only declare `Map<String,Object>`.

Shall I keep the compiler strict? Shall I issue warnings instead of errors?
Shall Neo4j documentation be updated to have a `Map` definition similar to `List`?

**Comment by fbiville** [comment]
The main point of this PR is to clarify what should be documented and what to do in case something is not.

**Comment by jexp** [comment]
Perhaps for 2) send a PR to make APOC compliant.

**Comment by fbiville** [comment]
After some thinking, I changed the compiler so that:

1. Node, Relationship and Path are valid input type (whether directly or in a collection)
2. Map value types are processed the same as List value types

In the end, neo4j-apoc failed to compile with only 2 errors: `Map` rawtype was used.

I'll send a PR to Neo4j docs in order to reflect the changes I did.

**Comment by jexp** [comment]
Can you add it in the pom.xml too? Thx :)

**Comment by jexp** [comment]
Really cool, thanks a lot @fbiville !!!

**Comment by fbiville** [comment]
Added to `pom.xml` here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/53 :)

**Pull request merged**
