### PR TITLE
Random Graph Generators

### PR DESCRIPTION
**Pull request by bachmanm**

### CODE REVIEW

**Comment by jexp** [comment]
Thanks a lot @bachmanm !!

Would you mind moving the detailed description into the docs in a separate generate.adoc file and only keep the overview in the readme?

Did you see the build failure? Dependency issue with faker?

**Comment by bachmanm** [comment]
will do - sorry about the build, I was using Maven, will fix gradle dependencies

**Comment by bachmanm** [comment]
OK, I think it should be ready. Thanks!

**Comment by jexp** [comment]
Looks good, thanks so much !

**Pull request merged**
