### PR TITLE
fixes #443 - Add apoc.export.cypher.schema to export all schema indexes and constraints to cypher

### LINKED ISSUE #443: Add apoc.export.cypher.schema to export all schema indexes and constraints to cypher
I've seen a number of situations, including after using the store-utils story-copy utility, when you want to copy the indexes and constraints from one database to another. It would be very handy to be able to do this via an APOC procedure.

### PR DESCRIPTION
**Pull request by AngeloBusato**

### CODE REVIEW

**Comment by jexp** [comment]
Looks good to me, perhaps some more docs

and tests for existence constraints?

**Comment by jexp** [comment]
@AngeloBusato please rebase and add the docs for what it would look like, with the export.
There is now

**Comment by jexp** [comment]
@AngeloBusato ping :)

**Comment by AngeloBusato** [comment]
@jexp  ok i'm working on this

**Comment by AngeloBusato** [comment]
@jexp Done

**Pull request merged**
