### PR TITLE
Update index.adoc

### PR DESCRIPTION
**Pull request by cuppajoeman**
Added extra required step for insatlling apoc onto neo4j server

### CODE REVIEW

**Comment by mneedham** [comment]
Hi @cuppajoeman,

Could you fill in the CLA (https://neo4j.com/developer/cla/) so that I can merge your commit?

Cheers, Mark

**Comment by fbiville** [comment]
@cuppajoeman could you sign the CLA, please?
If not, we'll close this pull request soon.

**Comment by cuppajoeman** [comment]
Hey @fbiville I sent the email signing the CLA

**Comment by fbiville** [comment]
Thanks, merging now!

**Pull request merged**
