### PR TITLE
 [#671] Provide Sørensen–Dice similarity function

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by ikwattro** [comment]
Why not leveraging already existing java libraries like https://github.com/tdebatty/java-string-similarity ?

**Comment by fbiville** [comment]
I personally tend to keep my third-party dependencies to a minimum, especially in this case, the implementation is even quite simple (I already had a specific Kotlin implementation around: https://github.com/graph-labs/open-data-with-neo4j/blob/master/similarity-extension/src/main/kotlin/fr/graphlabs/neo4j/StringSimilarityFunction.kt#L32)

I'm happy to pull a third-party implementation if you think re-implementing the algorithm is too risky.

**Comment by jexp** [comment]
@fbiville looks good, can you also add some docs in overview.adoc and text.adoc

**Comment by fbiville** [comment]
Shall I reduce the contribution to 1 UDF with a default language tag to "en-US"?

**Comment by jexp** [comment]
Yes please

**Comment by fbiville** [comment]
Done! (added the documentation for Levenshtein and Fuzzy Match as well)

**Pull request merged**
