### PR TITLE
Strict mode for apoc.meta.subGraph

### PR DESCRIPTION
**Pull request by ADTC**
This is PR for issue #45 

Examples are available in the issue.

### CODE REVIEW

**Comment by ADTC** [comment]
@jexp Travis build failing because of `CypherTest.java` again. Please see: c31f646 where your changes have caused several Travis build failures already.

```
Failed tests:   testMapParallel(apoc.cypher.CypherTest): expected:<100000> but was:<96030>

Tests run: 239, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:44 min
[INFO] Finished at: 2016-05-22T09:54:30+00:00
[INFO] Final Memory: 32M/334M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project apoc: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/travis/build/neo4j-contrib/neo4j-apoc-procedures/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

travis_time:end:0ddd164f:start=1463910703725707155,finish=1463910871718339454,duration=167992632299
[0K
[31;1mThe command "mvn test -Dmaven.javadoc.skip=true" exited with 1.[0m

Done. Your build exited with 1.
```

**Comment by jexp** [comment]
merged manually

**Comment by jexp** [comment]
thanks a lot

**Comment by ADTC** [comment]
Thank you!

**Pull request closed without merging**
