### PR TITLE
Fixes #176 - Additional documentation on apoc.triggers

### LINKED ISSUE #176: Additional documentation on apoc.triggers
I've been looking at using the apoc trigger functionality. It looks seriously powerful. 

That said I don't have a strong understanding of what statements  are accessible (e.g {createdLabels}, etc ) and what they contain. 

I'd love to see some documentation around this functionality and a few relatively complex examples (e.g update a label on a node, propagate some information to all connected nodes). 

Thank you!!

### PR DESCRIPTION
**Pull request by DanielBerton**
We created some examples and described the available statements, let me know if it's enough or is better add other documentation or examples

### CODE REVIEW

**Comment by jexp** [comment]
Cool, some notes.

1. Overview shouldn't include the file, that should be in index.adoc
2. Overview is only for a general listing, which will be replaced by just including the generated documentation csvs.
3. this seems to be mixed with the refactoring examples ? (which are also in overview.adoc, and be moved out). I don't mind if you leave them in a single PR but please move it to a separate adoc file and include that in the right place in index.adoc

Thanks

**Comment by DanielBerton** [comment]
@jexp ok we move the include in the index.adoc, we can put it in a separate section (like before `Appendix: Complete Overview` that contains all the overview.adoc)  or inside an existing one?
The refactoring examples was merged https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/399 we can fix it in this PR or in a new issue.

**Comment by DanielBerton** [comment]
I thought about modifying the refactor example in the issue https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/331 today

**Comment by DanielBerton** [comment]
@jexp PR updated

**Comment by jexp** [comment]
Cool, thanks a lot !

**Pull request merged**
