### PR TITLE
added apoc.date.systemTimezone() to retrieve the system timezone prog…

### PR DESCRIPTION
**Pull request by ikwattro**
…ramatically

### CODE REVIEW

**Comment by ikwattro** [comment]
For example, : 

```
RETURN apoc.date.formatTimezone(timestamp(), "ms", null, apoc.date.systemTimezone())
```

This would also https://github.com/neo-technology-field/knowledge-base/blob/be965a8a65d284760c3c0e2e8ca62547ee9d3cbb/articles/how-do-i-display-date-and-time-of-when-neo4j-was-started-and-other-metrics.adoc to return the correct value

**Comment by jexp** [comment]
Looks good to me, can you also add it to 3.0 ?

**Comment by jexp** [comment]
Oh and please add it to overview.adoc

And perhaps add the usage-example from the KB to the docs?

**Comment by ikwattro** [comment]
```
Looks good to me, can you also add it to 3.0 ?
```

Sure. 

---

```
Oh and please add it to overview.adoc

And perhaps add the usage-example from the KB to the docs?
```

Ok for overview. 

This is a private KB item, so maybe not.

**Pull request merged**
