### PR TITLE
Added sequences to path expander procedures

### PR DESCRIPTION
**Pull request by InverseFalcon**
Added `labelSequence` to path expander config parameters, allowing label filters to define a repeating sequence of nodes to expand.

Further commits also include `relationshipSequence`, and `sequence` (when both are needed)
Addresses #691.

### CODE REVIEW

**Comment by InverseFalcon** [comment]
Not quite ready for merge, I want to change a behavior with end node / termination node filtering for steps in the label sequence. I think I'd rather have the filters apply specifically to the labels matched, rather than at that current step in the sequence as a whole.

**Comment by InverseFalcon** [comment]
@jexp Okay, done here, ready for final review and merge.

Noted in the documentation some differences between the labelFilter and the labelSequence and sequence. 

Personally I prefer the newer behavior, so with 3.4 I'll be updating the labelFilter to match (we can also reuse the same evaluator between the label filter and label sequences, which will be a nice step as well).

**Comment by InverseFalcon** [comment]
I'm actually wondering now if it makes more sense to just keep `labelFilter` and `relationshipFilter` and just allow sequences in both of these. If there are entries separated by `,` it's a sequence, otherwise it's a filter for all node labels / relationships accordingly. 

The only conflict I can see (apart from some differences in behavior between the label filter and label sequences) is that label sequences can currently coexist with the label filter, so using both has to be possible. Maybe we don't actually need that.

Thoughts?

**Comment by InverseFalcon** [comment]
Made a decision. We'll reuse existing `labelFilter` and `relationshipFilter` for sequences, and standardize on a single syntax and behavior for label filters. 

Changed behaviors should be minimal, but are highlighted in the documentation.

**Comment by jexp** [comment]
Cool thanks!

**Pull request merged**
