### PR TITLE
NO AUTO Tries to deflake CREATE DATABASE tests

### PR DESCRIPTION
**Pull request by ncordon**
## What
Opens a session against `system` database directly before the `CREATE DATABASE` statements.

## Why
Reconcilarion and instance startup are async in Neo4j 5.x. In 5.x when the DBMS is started and bolt port is opened the only guarantee is that system is available.

### CODE REVIEW

**Comment by ncordon** [comment]
[[Essential builds failure] apoc.ttl.TTLMultiDbTest.testWithDefaultDatabaseAndSpecificDbWithLimitSpecified is failing on a Dev essential build](https://trello.com/c/oapkI4Hc/1009-essential-builds-failure-apocttlttlmultidbtesttestwithdefaultdatabaseandspecificdbwithlimitspecified-is-failing-on-a-dev-essenti)

**Comment by ncordon** [comment]
[[Essential builds failure] apoc.ttl.TTLMultiDbTest.testWithDefaultDatabaseWithTTLEnabled is failing on a Dev essential build](https://trello.com/c/kvzuQ93h/1010-essential-builds-failure-apocttlttlmultidbtesttestwithdefaultdatabasewithttlenabled-is-failing-on-a-dev-essential-build)

**Comment by ncordon** [comment]
[[Essential builds failure] apoc.ttl.TTLMultiDbTest.testWithSpecificDatabaseWithTTLDisabled is failing on a Dev essential build](https://trello.com/c/kN6ea95j/1036-essential-builds-failure-apocttlttlmultidbtesttestwithspecificdatabasewithttldisabled-is-failing-on-a-dev-essential-build)

**Comment by ncordon** [comment]
[[Essential builds failure] apoc.ttl.TTLMultiDbTest.testWithDefaultDatabaseAndSpecificDbWithScheduleSpecified is failing on a Dev essential build](https://trello.com/c/FmimOSzp/1011-essential-builds-failure-apocttlttlmultidbtesttestwithdefaultdatabaseandspecificdbwithschedulespecified-is-failing-on-a-dev-esse)

**Review by Lojjs — APPROVED** [review]
@ncordon I agree with you that it looks like both PRs are solving the same issue so probably this should not be needed. But if you would need it, it looks ok to use the system database

**Pull request merged**
