### PR TITLE
GephiWeightedRelationships

### PR DESCRIPTION
**Pull request by tomasonjo**
I added an optional weight property parameter, so you can pick which property do you want to use as a weight or set it at null for standard 1.0 weight

### CODE REVIEW

**Comment by jexp** [comment]
Make the weightProperty (call it weightProperty) optional (i.e. defaultValue="null")
and if none is set also send none.

If a weightProperty is given but none on the node, I'm not sure what the default should generally be for Gephi? 0 or 1 or ... ?

**Comment by jexp** [comment]
Also add a test or two for the new weightProperty

**Comment by tomasonjo** [comment]
I think this looks/works fine, will write a test or two tommorow... thanks for the help

**Comment by jexp** [comment]
Looks good to me, waiting for the tests before I merge.

**Comment by jexp** [comment]
Ping @tomasonjo please add the tests so that we can merge :)

**Comment by tomasonjo** [comment]
Tested it with Gephi running and the results were ok in Gephi. Also Gephi does not handle updating relationship weight, so I created a new label for each test. There seems to be some problem if data is not clean meaning that weight property is randomly a string/number or null within same call.

**Pull request merged**
