### PR TITLE
fix apoc.periodic.iterate not obeying concurrency

### PR DESCRIPTION
**Pull request by voutilad**
We've noticed that `apoc.periodic.iterate` has not been obeying the `concurrency` parameter setting. 

Looking into the code, it seems the procedure uses the default pooled executor when running with parallel=true, but the pool is `#cpus * 2`...so the concurrency ends up actually being **2x** the cpu cores and not what the user sets.

This PR changes the behavior to use a set cap via an `AtomicInteger` and keeps the same Future creation/submission logic but adds the decrement of the counter to the future's callback. 

If `parallel == false`, the gating is short-circuited at the expense of some small overhead for manipulating the `AtomicInteger` counter (for now?) and the single-threaded executor will force concurrency to zero.

### CODE REVIEW

**Comment by voutilad** [comment]
This isn't ready to merge...should have set it to a Draft PR...need to validate the cancellation behavior. Right now my manual testing has me questioning how the batch counters are being incremented during a cancellation.

**Comment by voutilad** [comment]
Ok, it might be my work is just uncovering other existing issues with `apoc.periodic.iterate` such as the inner transactions working on the batches don't get properly interrupted if the outer-most transaction is asked to terminate.

**Comment by voutilad** [comment]
Seems someone recently reported this problem: https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1769

**Comment by conker84** [comment]
@voutilad you should be able to convert it to draft if you want

**Pull request merged**
