### PR TITLE
fixes #425 - allow apoc.cypher.runFile to take multiple files and run each file in a different tx

### LINKED ISSUE #425: allow apoc.cypher.runFile to take multiple files and run each file in a different tx
the files should be imported in order.

so that we can use the separate files produced by apoc.export.cypher with the directory option.

### PR DESCRIPTION
**Pull request by DanielBerton**

### CODE REVIEW

**Comment by jexp** [comment]
@DanielBerton we cannot just change the API

So a separate, new procedure `runFiles` (with s) instead that takes a list makes sense.

Then we also have to make `runStatements` to

1. support schema operations (and test mixed schema + data operations in different files too)
2. always run the file in a new tx
3. make sure that the TOMBSTONE is passed *after* the other operations have finished (I think they are blocking but I am not 100% sure)

**Comment by jexp** [comment]
@DanielBerton ping?

**Comment by jexp** [comment]
We said we wanted to keep runFile

and add a runFiles with a list of files each of which is executed separately.
And a runFilesSchema which uses mode=SCHEMA/DBMS demarcation and schema transactions?

**Comment by DanielBerton** [comment]
@jexp yes I'm preparing a new PR

**Comment by DanielBerton** [comment]
@jexp  fixed with @inserpio support. We have two different apoc for `data` and `schema` files. 
Also we start a new transaction per file, marked with `mode.SCHEMA` the new procedures and introduced `TOMBSTONE`

**Pull request merged**
