### PR TITLE
fix 1184

### LINKED ISSUE #1184: apoc.export.csv.query() does not register duration.inSeconds formatting
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)

`CALL apoc.export.csv.query(" ... ... RETURN duration.inSeconds(a.timeStamp, b.timeStamp) ..." )`
should return "P0M0DT2651S" in the csv file (only seconds)

## Actual Behavior (Mandatory)

wrongly returns "PT44M11S" in csv file (minutes and seconds)
(when queried directly on Neo4j, it correctly returns "P0M0DT930S" on the dashboard)

### Simple Dataset (where it's possible)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Screenshots (where it's possible)

Screen Shot 2019-04-28 at 11 31 00 AM

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

### PR DESCRIPTION
**Pull request by enriquezrene**
Fixes #1184
Adding a format method for DurationValue data types

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - Add a new method to format DurationValue data types

### CODE REVIEW

**Comment by jexp** [comment]
Perhaps rather add an separate user defined function for your output-format and then you can use that during your export?

**Comment by enriquezrene** [comment]
Hey @conker84 you're right, but the statement is asking for a value represented using seconds only.
@jexp I think that's why `duration.inSeconds` was added in the statement, or do you think the user should provide any other metadata for it?

**Comment by jexp** [comment]
@enriquezrene ah I see what you're saying sorry I overlooked that.
That then seems to be an issue in Neo4j itself that we have to differentiate with the duration values.

**Comment by jexp** [comment]
@conker84 what's the state on this PR?

**Comment by fbiville** [comment]
Closing this as we have not heard from the author. Feel free to reopen if needed.

**Pull request closed without merging**
